### ISSUE TITLE
[反馈/建议]项目无法在GTNH的2.4.1至2.5.1版本上使用

### ISSUE THREAD

**Issue by ziningyue** [vfyjxf/NEI-Utilities#11]
重新创建一个无任何添加的GTNH2.5.1版本，采用hmcl下载的1.7.10以及forge1614版本。
直接添加由wiki上下载的客户端版本，在进入本地世界后，该mod无法生效。即点击NEI合成表后无法记录。
在GTNH2.4.1版本中，进入本地世界后Mod无效，即无法记录。同时进入服务器后，手动点击NEI合成表后，游戏直接崩溃；如果采用R键或U键进行合成表选择，可正常显示合成表，但无法记录。
该合成表的界面为，进入世界之后按E打开背包之后的右侧合成栏。

**Comment by RealSilverMoon** [comment]
fixed
