### ISSUE TITLE
模组疑似在GTNH中导致崩溃

### ISSUE THREAD

**Issue by 502y** [vfyjxf/NEI-Utilities#2]
安装本模组后，在服务器中左键单击右侧NEI中搜索的物品“超级缸 III"和”超级缸 V“后崩溃，崩溃报告如下。
[crash-2022-10-06_09.52.02-client.txt](https://github.com/vfyjxf/NEI-Utilities/files/9720492/crash-2022-10-06_09.52.02-client.txt)

[crash-2022-10-06_09.34.14-client.txt](https://github.com/vfyjxf/NEI-Utilities/files/9720491/crash-2022-10-06_09.34.14-client.txt)
使用”U“键或”R“键及在其打开的合成表中使用左键或右键单击物品不会导致崩溃。

**Comment by vfyjxf** [comment]
看起来是gtnh的nei又修改了部分代码导致了不兼容，我到时候修修看。
