### ISSUE TITLE
Error while playing GTNH version 2.2.3 with this mod

### ISSUE THREAD

**Issue by Yecgaa1** [vfyjxf/NEI-Utilities#3]
![image](https://user-images.githubusercontent.com/38446391/205093091-e68981a2-fbcb-46ec-a7c9-20ffebd7e624.png)
Here is the crash report, thanks
[crash-2022-12-01_23.27.38-client.txt](https://github.com/vfyjxf/NEI-Utilities/files/10133746/crash-2022-12-01_23.27.38-client.txt)

**Comment by Yecgaa1** [comment]
Incidentally, I'm just an ordinary mc player, so I have no clue about the cause of the problem, I'm sorry, but I'm willing to provide you with more information, thank you.

**Comment by Yecgaa1** [comment]
![image](https://user-images.githubusercontent.com/38446391/205096880-88930761-3ee3-4d2f-9c69-fc861881e012.png)
Incidentally, I found that I had downloaded version 0.1.8 from the release page, but it was recognized as version 0.1.4 in mmc

**Comment by vfyjxf** [comment]
I guess it might be because you didn't update gtnh nei, please make sure the version of nei is higher than 2.3.14 and nei utilities are really updated, mmc can't recognize the correct version information because there is a small problem with the packaging of the mod.

**Comment by Yecgaa1** [comment]
![image](https://user-images.githubusercontent.com/38446391/205488452-5c726536-c23e-49d2-b077-35dc4180c511.png)
I'm not sure, because I chose to download the latest GTNH version 2.3.3, but it provides NEI as version 2.3.7, am I misunderstanding something

**Comment by vfyjxf** [comment]
Maybe you can lower the version of nei utilities, I'm not sure, I can only make sure that 0.1.8 supports 2.3.14 and later versions.

**Comment by AoaoMH** [comment]
> Maybe you can lower the version of nei utilities, I'm not sure, I can only make sure that 0.1.8 supports 2.3.14 and later versions.

I encountered the same problem. I used GTNH stable Edition, 2.2.0.0.
The nei version is 2.3.7-GTNH, with frequent crash.

**Comment by Yecgaa1** [comment]
Now I use 0.1.7 with NEI 2.3.7 in GTNH 2.3.3 and it works well

**Comment by AoaoMH** [comment]
> Now I use 0.1.7 and it works well

感谢，我去下载一下。
