### ISSUE TITLE
作弊模式刷物品时崩溃

### ISSUE THREAD

**Issue by Mobius0526** [vfyjxf/NEI-Utilities#4]
使用gtnh整合包，使用本mod 0.1.8版本
nei开启作弊模式，点击历史记录栏内物品时有几率崩溃
[crash-2023-01-24_21.11.36-client.txt](https://github.com/vfyjxf/NEI-Utilities/files/10490025/crash-2023-01-24_21.11.36-client.txt)

**Comment by vfyjxf** [comment]
退版本看看，貌似是Nei utilities太新了不兼容旧nei

**Comment by Mobius0526** [comment]
退到0.1.7确实解决了。不过0.1.7有一个显示bug，鼠标放在历史栏的物品上时物品会高亮显示，上面NEI的物品对应位置也会高亮显示
