### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by BurNingcl0ud** [vfyjxf/NEI-Utilities#5]
GTNH2.2.0.0单人游戏,在使用[NEI-Utilities]时概率发生崩溃（NEI-Utilities-1.7.10-0.1.8）
GTNH2.2.0.0single play,Probability crashes when using [NEI-Utilities].（NEI-Utilities-1.7.10-0.1.8）
可能是nei的gui渲染出错了
It could be that Nei's GUI rendering went wrong
crashreport：https://paste.ubuntu.com/p/ZzX6xWPZv6/

**Comment by vfyjxf** [comment]
退版本看看（Nei utilities）

**Comment by BurNingcl0ud** [comment]
谢谢，换成[NEI-Utilities-1.7.10-0.1.7]之后问题已解决
